### ISSUE TITLE
Remove as many occurences of `tokio::Runtime::block_on` from the codebase as possible

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#173]
Currently, our codebase contains numerous instances of `tokio::Runtime::block_on` calls to call `async` code from sync code. While this is necessary when interacting with `revm`, it unnecessarily causes "freezes" when Hardhat is interacting with EDR through napi. This can be avoided by implementing the EDR traits using the [`#[async_trait]` procedural macro](https://docs.rs/async-trait/latest/async_trait/).

**Comment by Wodann** [comment]
If my understanding of JavaScript is correct, it only executes one thread at a time. The way it achieves asynchronous work is through polling of promises. This only works as long as promises don't block. Even a callback-based approach will "freeze" if we keep the `block_on` calls, so it wouldn't alleviate the situation

**Comment by agostbiro** [comment]
I’m not familiar with the details of napi, but in theory we could move the
execution of the bulk of the Rust code to another thread from Rust when JS
calls into Rust and return immediately in the JS thread. Then once the Rust
code is done, it could pass back the result with the callback it received
from JS. This way we could avoid blocking the JS thread.

If we moved the bulk of the Rust code to a tokio worker thread with
‘spawn’, that’d also allow removing ‘block_on’ calls, since the bulk of the
Rust code would be executed in the context of a tokio runtime.

**Comment by Wodann** [comment]
We discussed this on a call, but this is already how our napi implementation works.
